#ifndef _MENU_H_
#define _MENU_H_

typedef enum {
    MS_STARTUP, MS_MULTIPLAYER, MS_OPTIONS, MS_HELPABOUT, MS_WAITING, MS_JOINING
} MENUSTATE;

#define SINGLE_BUTTON       0
#define MULTIP_BUTTON       1
#define OPTIONS_BUTTON      2
#define HELPABOUT_BUTTON    3
#define EXIT_BUTTON         4
#define NEW_BUTTON          5
#define JOIN_BUTTON         6
#define BACK_BUTTON         7
#define RESUME_BUTTON       8

#define SINGLE_OFFSETX      216
#define SINGLE_OFFSETY      176
#define SINGLE_OFFSETX2     SINGLE_OFFSETX + 365
#define SINGLE_OFFSETY2     SINGLE_OFFSETY + 70

#define MULTIP_OFFSETX      216
#define MULTIP_OFFSETY      SINGLE_OFFSETY2 + 5
#define MULTIP_OFFSETX2     MULTIP_OFFSETX + 365
#define MULTIP_OFFSETY2     MULTIP_OFFSETY + 70

#define OPTIONS_OFFSETX     216
#define OPTIONS_OFFSETY     MULTIP_OFFSETY2 + 5
#define OPTIONS_OFFSETX2    OPTIONS_OFFSETX + 365
#define OPTIONS_OFFSETY2    OPTIONS_OFFSETY + 70

#define HELPABOUT_OFFSETX   216
#define HELPABOUT_OFFSETY   OPTIONS_OFFSETY2 + 5
#define HELPABOUT_OFFSETX2  HELPABOUT_OFFSETX + 365
#define HELPABOUT_OFFSETY2  HELPABOUT_OFFSETY + 70

#define EXIT_OFFSETX        16
#define EXIT_OFFSETY        OPTIONS_OFFSETY2 + 5
#define EXIT_OFFSETX2       EXIT_OFFSETX + 120
#define EXIT_OFFSETY2       EXIT_OFFSETY + 70

#define BACK_OFFSETX        216
#define BACK_OFFSETY        OPTIONS_OFFSETY2 + 5
#define BACK_OFFSETX2       BACK_OFFSETX + 365
#define BACK_OFFSETY2       BACK_OFFSETY + 70

#define BACK2_OFFSETX       8
#define BACK2_OFFSETY       394
#define BACK2_OFFSETX2      BACK_OFFSETX + 365
#define BACK2_OFFSETY2      BACK_OFFSETY + 70

#define NEW_OFFSETX         216
#define NEW_OFFSETY         176
#define NEW_OFFSETX2        NEW_OFFSETX + 365
#define NEW_OFFSETY2        NEW_OFFSETY + 70

#define JOIN_OFFSETX        216
#define JOIN_OFFSETY        NEW_OFFSETY2 + 5
#define JOIN_OFFSETX2       JOIN_OFFSETX + 365
#define JOIN_OFFSETY2       JOIN_OFFSETY + 70

#endif //_MENU_H_
